ECOVAX/Controllers/DangNhapController.cs
using ECOVAX.Models;
using ECOVAX.Providers;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECOVAX.Controllers
{
    public class DangNhapController : Controller
    {
        // GET: DangNhap
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult BeginLogin(string tenDN, string mk)
        {
            DataTable tb = DataProvider.ExecuteQuery("SELECT T1.IdTaiKhoan," +
                                                        " T1.TenTK," +
                                                        " T1.MatKhau," +
                                                        " T2.Ten," +
                                                        " T2.SDT," +
                                                        " T2.CMND," +
                                                        " T1.UpdateTime" +
                                                        " FROM tblTaiKhoan T1 LEFT JOIN tblThongTin T2 ON T1.IdThongTin = T2.Id" +
                                                        " WHERE T1.TenTK LIKE '" + tenDN + "'" +
                                                        " AND T1.MatKhau LIKE '" + mk + "'");

            if (tb.Rows.Count > 0)
            {
                UserModel user = new UserModel(tb.Rows[0]);
                Session[Constant.USER_INFO] = user;
                return Json("{}", JsonRequestBehavior.AllowGet);
            }
            return new HttpStatusCodeResult(500, null);
        }
    }
}

ECOVAX/Views/DangNhap/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link href="~/Content/dashboard/css/main.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="~/Content/image/logo.png" />
    <!-- Font-icon css-->
    <link href="~/Content/fontawesome-pro-5.13.0-web/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Content/index.css" rel="stylesheet" />
    <title>Đăng nhập - Cổng tiêm chủng ECOVAX</title>
</head>
<body>
    <div class="window_lock_background window_loading_screen" id="windowLoadingScreen">
        <div class="lds-ellipsis">
            <div></div><div></div><div></div><div></div>
        </div>
    </div>

    <div class="alert popup-alert alert-success" role="alert" id="alertDialog">
        This is a warning alert—check it out!
    </div>
    <section class="material-half-bg">
        <div class="cover"></div>
    </section>
    <section class="login-content">
        <div class="logo">
            <h1>Cổng tiêm chủng ECOVAX</h1>
        </div>
        <div class="login-box">

            @using (Html.BeginForm("BeginLogin", "DangNhap", FormMethod.Post, new { id = "loginForm", @class = "login-form" }))
            {
<h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>Đăng nhập</h3>
                <div class="form-group">
                    <label class="control-label">Tên đăng nhập</label>
                    <input class="form-control" type="text" placeholder="Tên đăng nhập" name="TenDangNhap" id="TenDangNhap" autofocus>
                </div>
                                <div class="form-group">
                                    <label class="control-label">Mật khẩu</label>
                                    <input class="form-control" type="password" placeholder="Mật khẩu" name="MatKhau" id="MatKhau">
                                </div>
                                                <div class="form-group">
                                                    <div class="utility">
                                                        @*<div class="animated-checkbox">
                                                                <label>
                                                                    <input type="checkbox"><span class="label-text">Stay Signed in</span>
                                                                </label>
                                                            </div>*@
                                                        <p class="semibold-text mb-2"><a href="#" data-toggle="flip">Quên mật khẩu ?</a></p>
                                                    </div>
                                                </div>
                                                                <div class="form-group btn-container">
                                                                    <button class="btn btn-primary btn-block" id="btnLogin" type="button"><i class="fa fa-sign-in fa-lg fa-fw"></i>Đăng nhập</button>
                                                                </div>}
            <form class="forget-form" action="index.html">
                <h3 class="login-head"><i class="fa fa-lg fa-fw fa-lock"></i>Quên mật khẩu ?</h3>
                <div class="form-group">
                    <label class="control-label">EMAIL</label>
                    <input class="form-control" type="text" placeholder="Email">
                </div>
                <div class="form-group btn-container">
                    <button class="btn btn-primary btn-block"><i class="fa fa-unlock fa-lg fa-fw"></i>RESET</button>
                </div>
                <div class="form-group mt-3">
                    <p class="semibold-text mb-0"><a href="#" data-toggle="flip"><i class="fa fa-angle-left fa-fw"></i> Quay về đăng nhập</a></p>
                </div>
            </form>
        </div>
    </section>
    <!-- Essential javascripts for application to work-->
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.min.js"></script>
    <script src="~/Scripts/index.js"></script>
    <script type="text/javascript">
        // Login Page Flipbox control
        $('.login-content [data-toggle="flip"]').click(function () {
            $('.login-box').toggleClass('flipped');
            return false;
        });
        $(document).ready(function () {
            $("#loginForm").validate({
                errorPlacement: function (error, element) {
                    error.insertAfter(element);  // default placement for everything else
                },
                rules: {
                    TenDangNhap: {
                        required: true,
                    },
                    MatKhau: {
                        required: true,
                    },
                }
            });
            $("#btnLogin").on('click', function () {
                if ($("#loginForm").valid()) {
                    $.ajax({
                        type: "GET",
                        dataType: "json",
                        data: {
                            tenDN: $("#TenDangNhap").val(),
                            mk: $("#MatKhau").val()
                        },
                        contentType: "application/json; charset=utf-8",
                        url: '/DangNhap/BeginLogin',
                        success: function (jsonResult) {
                            location.href = "/Dashboard";
                        },
                        error: function () {
                            showDangerAlert("Tên đăng nhập hoặc mật khẩu không đúng");
                        }
                    });
                }
            });
        });
    </script>
</body>
</html>