ECOVAX/Models/PheDuyetGDKViewModel.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ECOVAX.Models
{
    public class PheDuyetGDKViewModel : BaseModel
    {
        public List<DanhMucSangLocModel> listDanhMucSangLoc { get; set; }
        public string IdGiayGK { get; set; }
        public string BuoiTiemThucTe { get; set; }
        public string BuoiTiemMongMuon { get; set; }
        public string NgayTiemMongMuon { get; set; }
        public string UpdateTime { get; set; }
        public DateTime NgayTiemThucTe { get; set; }
        public string VaccineMuiMot { get; set; }
        public string SoMui { get; set; }
        public string TrangThaiPD { get; set; }
        public string NgayTiemMuiMot { get; set; }
        public string IdDTC { get; set; }
        public string TenNguoiDK { get; set; }
        public string TenNguoiLH { get; set; }
        public string SDTNguoiLH { get; set; }
        public string SDTNguoiDK { get; set; }
        public string QuanHe { get; set; }
        public string NgheNghiep { get; set; }
        public string Email { get; set; }
        public string NhomUuTien { get; set; }
        public string CMND { get; set; }
        public string NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Vaccine { get; set; }
        public List<SelectListItem> DdlBuoiTiem { get; set; }
        public List<SelectListItem> DdlTrangThaiPD { get; set; }
        public List<SelectListItem> DdlVaccine { get; set; }
        public PheDuyetGDKViewModel()
        {
            listDanhMucSangLoc = new List<DanhMucSangLocModel>();
            DdlBuoiTiem = new List<SelectListItem>();
            DdlTrangThaiPD = new List<SelectListItem>();
            DdlVaccine = new List<SelectListItem>();
        }
    }
}

ECOVAX/Controllers/DangKyTiemController.cs
using ECOVAX.Models;
using ECOVAX.Providers;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace ECOVAX.Controllers
{
    [OutputCache(NoStore = true, Duration = 0)]
    public class DangKyTiemController : Controller
    {
        private static GiayDangKyViewModel giayDangKyViewModel;
        private static PhieuSangLocViewModel phieuSangLocViewModel;
        public ActionResult Index()
        {
            giayDangKyViewModel = new GiayDangKyViewModel();

            DataTable tb = DataProvider.ExecuteQuery("SELECT * FROM tbl" +
                "DdlQuanHe");
            for (int i = 0; i < tb.Rows.Count; i++)
            {
                string text = tb.Rows[i]["Ten"].ToString();
                string value = tb.Rows[i]["Id"].ToString();
                giayDangKyViewModel.DdlQuanHe.Add(new SelectListItem() { Text = i + 1 + ". " + text, Value = value });
            }

            tb = DataProvider.ExecuteQuery("SELECT * FROM tblDdlDoiTuongUuTien");
            for (int i = 0; i < tb.Rows.Count; i++)
            {
                string text = tb.Rows[i]["Ten"].ToString();
                string value = tb.Rows[i]["Id"].ToString();
                giayDangKyViewModel.DdlDoiTuongUuTien.Add(new SelectListItem() { Text = i + 1 + ". " + text, Value = value });
            }

            tb = DataProvider.ExecuteQuery("SELECT * FROM tblVaccine");
            for (int i = 0; i < tb.Rows.Count; i++)
            {
                string text = tb.Rows[i]["TenVaccine"].ToString();
                string value = tb.Rows[i]["TenVaccine"].ToString();
                giayDangKyViewModel.DdlVaccine.Add(new SelectListItem() { Text = text, Value = value });
            }

            giayDangKyViewModel.DdlGioiTinh = DropDownList.DDL_GIOITINH;

            giayDangKyViewModel.DdlSoMui = DropDownList.DDL_SOMUI;

            giayDangKyViewModel.DdlBuoiTiem = DropDownList.DDL_BUOITIEM;

            return View("Index", giayDangKyViewModel);
        }

        [HttpPost]
        public ActionResult SubmitPhieuDangKy(GiayDangKyViewModel formItem)
        {
            giayDangKyViewModel = formItem;
            GetDanhMucSangLoc();
            return RedirectToAction("SangLoc");
        }

        public ActionResult SangLoc()
        {
            return View("PhieuSangLoc", phieuSangLocViewModel);
        }

        [HttpPost]
        public ActionResult SubmitPhieuSangLoc(PhieuSangLocViewModel formItem)
        {
            phieuSangLocViewModel = formItem;
            return RedirectToAction("XacNhanTiem");
        }

        public ActionResult XacNhanTiem()
        {
            return View("XacNhanTiem");
        }

        [HttpPost]
        public ActionResult SubmitXacNhanTiem()
        {
            return RedirectToAction("HoanTat");
        }
        public ActionResult HoanTat()
        {
            if (giayDangKyViewModel.TenNguoiLH != null && giayDangKyViewModel.TenNguoiLH.Trim() != "")
            {
                InsertGiayDangKy();
            }
            return View("HoanTat");
        }

        private void GetDanhMucSangLoc()
        {
            phieuSangLocViewModel = new PhieuSangLocViewModel();
            DataTable tb = DataProvider.ExecuteQuery("SELECT * FROM tblPhieuSangLoc WHERE DeleteFlag = 0");
            DanhMucSangLocModel danhMuc;
            foreach (DataRow row in tb.Rows)
            {
                danhMuc = new DanhMucSangLocModel();
                danhMuc.IdDanhMuc = (int)row["IdPhieuSangLoc"];
                danhMuc.TenDanhMuc = row["TenDanhMuc"].ToString();
                phieuSangLocViewModel.listDanhMucSangLoc.Add(danhMuc);
            }
        }

        private void InsertGiayDangKy()
        {
            if (giayDangKyViewModel != null && phieuSangLocViewModel != null)
            {
                string idGiayDK = DataProvider.GetNewId(Constant.ID_GIAYDK_PREFIX);
                giayDangKyViewModel.DiaChi += " " + giayDangKyViewModel.DiaChiHanhChinh;

                string idThongTin;
                //Check Exist Thong tin
                DataTable tb = DataProvider.ExecuteQuery("SELECT Id FROM tblThongTin WHERE CMND LIKE '" + giayDangKyViewModel.CMND + "'");
                if (tb.Rows.Count > 0)
                {
                    idThongTin = tb.Rows[0]["Id"].ToString();
                }
                else
                {
                    tb = DataProvider.ExecuteQuery("EXEC INSERT_tblThongTin @Ten , @SDT , @CMND , @DiaChi , @NgaySinh , @GioiTinh",
                        new object[] {giayDangKyViewModel.TenNguoiDK, giayDangKyViewModel.SDTNguoiDK, giayDangKyViewModel.CMND,
                        giayDangKyViewModel.DiaChi, giayDangKyViewModel.NgaySinh, giayDangKyViewModel.GioiTinh});

                    idThongTin = tb.Rows[0]["Id"].ToString();
                }

                if (giayDangKyViewModel.SoMui == "1")
                {
                    giayDangKyViewModel.TenVaccineMuiMot = null;
                    giayDangKyViewModel.NgayTiemMuiMot = null;
                }
                object[] giayDKObject = new object[]
                {
                    idGiayDK,
                    idThongTin,
                    giayDangKyViewModel.Email,
                    giayDangKyViewModel.NhomUuTien,
                    giayDangKyViewModel.NgheNghiep,
                    giayDangKyViewModel.TenNguoiLH,
                    giayDangKyViewModel.SDTNguoiLH,
                    giayDangKyViewModel.QuanHe,
                    giayDangKyViewModel.SoMui,
                    Constant.TRANG_THAI_CHO_XN,
                    giayDangKyViewModel.TenVaccineMuiMot,
                    giayDangKyViewModel.NgayTiemMuiMot,
                    giayDangKyViewModel.NgayTiem,
                    giayDangKyViewModel.BuoiTiem
                };

                DataProvider.ExecuteNonQuery("EXEC INSERT_tblGiayDangKy @IdGiayDK ," +
                                                                       " @IdThongTin , " +
                                                                       " @Email , " +
                                                                       " @NhomUuTien , " +
                                                                       " @NgheNghiep , " +
                                                                       " @TenNguoiLH , " +
                                                                       " @SDTNguoiLH , " +
                                                                       " @QuanHe , " +
                                                                       " @SoMui , " +
                                                                       " @TrangThaiPD , " +
                                                                       " @TenVaccineMuiMot , " +
                                                                       " @NgayTiemMuiMot , " +
                                                                       " @NgayTiem ," +
                                                                       " @BuoiTiem ", giayDKObject);

                foreach (DanhMucSangLocModel item in phieuSangLocViewModel.listDanhMucSangLoc)
                {
                    DataProvider.ExecuteNonQuery("EXEC INSERT_tblChiTietPhieuSangLoc @IdGiayDK , @IdPhieuSangLoc , @TrangThai", new object[] {
                    idGiayDK, item.IdDanhMuc, item.TrangThai });
                }

                giayDangKyViewModel = null;
            }
        }

        [HttpGet]
        public ActionResult CheckNgayTiemMuiMot(string idVaccine, string ngayTiem, string ngayTiemMongMuon)
        {
            if (!string.IsNullOrEmpty(idVaccine))
            {
                DataTable tb = DataProvider.ExecuteQuery("SELECT * FROM tblVaccine WHERE TenVaccine LIKE '" + idVaccine + "'");
                int thoiHanTiem = (int)tb.Rows[0]["ThoiHanTiem"];
                DateTime dateCheck = DateTime.Now;
                if (!string.IsNullOrEmpty(ngayTiemMongMuon))
                {
                    dateCheck = DateTime.Parse(ngayTiemMongMuon);
                }
                TimeSpan ts = dateCheck - DateTime.Parse(ngayTiem);
                int days = (int)ts.TotalDays;
                if (days <= thoiHanTiem)
                {
                    string message = "Ngày tiêm mũi một phải nhỏ hơn ngày hiện tại ít nhất " + thoiHanTiem + " ngày";
                    if (!string.IsNullOrEmpty(ngayTiemMongMuon))
                    {
                        message = "Ngày tiêm mong muốn phải lớn hơn ngày tiêm mũi một ít nhất " + thoiHanTiem + " ngày";
                    }
                    return Json(new
                    {
                        status = "error",
                        message = message
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json("{}", JsonRequestBehavior.AllowGet);
        }
    }
}

ECOVAX/Views/PheDuyetGDK/Index.cshtml
@model ECOVAX.Models.PheDuyetGDKViewModel
@{
    Layout = "~/Views/Shared/_Popup.cshtml";
}
@section popupJS
{
    <script src="~/Scripts/api-hanh-chinh-vn-dashboard.js"></script>
    <script src="~/Scripts/phe-duyet-gdk.js"></script>
}
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            @using (Html.BeginForm("SubmitPhieuDangKy", "DangKyTiem",
                FormMethod.Post, new { id = "pheDuyetForm", @class = "w-100" }))
            {
                <div class="row">
                    <div class="col-md-6">
                        <h3 class="tile-title">Thông tin phê duyệt</h3>
                        <div class="form-group">
                            <label>
                                Tên người liên hệ:&emsp; @Model.TenNguoiLH
                            </label>
                            <br />
                            <label>
                                SĐT người liên hệ:&emsp; @Model.SDTNguoiLH
                            </label>
                            <br />
                            <label>
                                Quan hệ với người đăng ký:&emsp; @Model.QuanHe
                            </label>
                        </div>

                        <div class="form-group">
                            <label>
                                Tên người đăng ký:&emsp; @Model.TenNguoiDK
                            </label>
                            <br />
                            <label>
                                CMND/ CCCD:&emsp; @Model.CMND
                            </label>
                            <br />
                            <label>
                                Ngày sinh:&emsp; @Model.NgaySinh
                            </label>
                            <br />
                            <label>
                                SDT người ĐK:&emsp; @Model.SDTNguoiDK
                            </label>
                            <br />
                            <label>
                                Địa chỉ:&emsp; @Model.DiaChi
                            </label>
                            <br />
                            <label>
                                Nghề nghiệp:&emsp; @Model.NgheNghiep
                            </label>
                            <br />
                            <label>
                                Nhóm ưu tiên:&emsp; @Model.NhomUuTien
                            </label>
                            <br />
                            <label>
                                Buổi tiêm mong muốn:&emsp; @Model.BuoiTiemMongMuon
                            </label>
                            <br />
                            <label>
                                Ngày tiêm mong muốn:&emsp; <span id="txtNgayTiemMongMuon" class="font-weight-bold">@Model.NgayTiemMongMuon</span>
                            </label>
                            <br />
                            <label>
                                Số mũi đăng ký:&emsp; <span class="font-weight-bold">@Model.SoMui</span>
                            </label>
                        </div>
                        @if (Model.SoMui != "1")
                        {
                            <div class="form-group">
                                <label>
                                    Tên vắc xin mũi một:&emsp;<span class="font-weight-bold"> @Model.VaccineMuiMot</span>
                                </label>
                                <br />
                                <label>
                                    Ngày tiêm mũi một:&emsp;<span class="font-weight-bold"> @Model.NgayTiemMuiMot</span>
                                </label>
                            </div>
                        }
                        <div class="form-group">
                            <label class="required">
                                Trạng thái phê duyệt
                            </label>
                            @Html.DropDownListFor(m => m.TrangThaiPD, Model.DdlTrangThaiPD,
                               new
                               {
                                   id = "ddlTrangThai",
                                   @class = "form-control",
                                   placeholder = "Chọn trạng thái..."
                               })
                        </div>
                        <div class="form-group">
                            <label class="required">
                                Ngày tiêm
                            </label>
                            <input class="form-control" type="date" placeholder="Ngày tiêm" id="ngayTiem" name="NgayTiemThucTe" value="@Model.NgayTiemThucTe" />
                        </div>
                        <div class="form-group">
                            <label class="required">
                                Buổi tiêm
                            </label>
                            @Html.DropDownListFor(m => m.BuoiTiemThucTe, Model.DdlBuoiTiem,
                               new
                               {
                                   id = "ddlBuoiTiem",
                                   @class = "form-control",
                                   title = "Chọn buổi tiêm..."
                               })
                        </div>
                        <div class="form-group">
                            <label class="required">
                                Phân bổ đến điểm tiêm chủng
                            </label>
                            <input id="idDTC" maxlength="10" type="text" class="form-control" placeholder="Nhập mã điểm tiêm chủng" name="IdDTC" value="@Model.IdDTC" />
                        </div>
                        <div class="form-group">
                            <label class="required">
                                Chỉ định vắc xin
                            </label>
                            @Html.DropDownListFor(m => m.Vaccine, Model.DdlVaccine,
                               new
                               {
                                   id = "ddlVaccine",
                                   @class = "form-control",
                                   title = "Chọn vắc xin..."
                               })
                        </div>
                        <div class="tile-footer text-right mt-4">
                            <button class="btn btn-primary" type="button" id="btnSubmit">Phê duyệt</button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h3 class="tile-title">Thông tin phiếu sàng lọc</h3>
                        <table class="table table-hover table-bordered" id="tblPhieuSangLoc">
                            <thead>
                                <tr>
                                    <th>Tên danh mục</th>
                                    <th>Trạng thái</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (var index = 0; index < Model.listDanhMucSangLoc.Count; index++)
                                {
                                    <tr>
                                        <td>
                                            @(index + 1).
                                            @Model.listDanhMucSangLoc[index].TenDanhMuc
                                        </td>
                                        <td class="text-center p-0">
                                            <label>
                                                @Model.listDanhMucSangLoc[index].TrangThai
                                            </label>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            }
        </div>
        <div class="tile">
            <div class="tile-title">
                <h3>Tra cứu điểm tiêm chủng theo vắc xin chỉ định</h3>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-4">
                        <button class="btn btn-dark" type="button" id="btnSearch">Tìm kiếm</button>
                    </div>
                </div>
            </div>
            <div class="col-md-12 row">
                <table class="table table-hover table-bordered" id="tblDTC">
                    <thead>
                        <tr>
                            <th>Mã điểm tiêm chủng</th>
                            <th>Tên</th>
                            <th>Địa chỉ</th>
                            <th>Thời gian làm việc</th>
                            <th>Người phụ trách</th>
                            <th>SĐT</th>
                            <th>Lô vắc xin</th>
                            <th>Số lượng vắc xin</th>
                            <th>Hạn sử dụng</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>